apiVersion: v1
kind: ServiceAccount
metadata:
  name: lummo-service-account
  namespace: lummo
  labels:
    account: lummo-service-account 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: lummo-cluster-role
  labels:
    app: lummo-cluster-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: lummo-cluster-role-binding
  labels:
    app: lummo-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lummo-cluster-role
subjects:
  - name: lummo-service-account
    kind: ServiceAccount
    namespace: lummo